CREATE TABLE CIUDADES (
  ciudId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ciudNombre VARCHAR(35) NOT NULL
);
CREATE TABLE BARRIOS (
  barrId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ciudId INT(5) NOT NULL,
  FOREIGN KEY (ciudId) REFERENCES CIUDADES(ciudId) ON DELETE CASCADE
);
CREATE TABLE CASAS (
  casaId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  barrId INT(5) NOT NULL,
  casaEstrato INT(1) CHECK (1 OR 2 OR 3 OR 4 OR 5 OR 6),
  casaDireccion VARCHAR(35),
  FOREIGN KEY (barrId) REFERENCES BARRIOS(barrId) ON DELETE CASCADE
);
CREATE TABLE USUARIOS (
  usuaId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  casaId INT(5) NOT NULL,
  usuaIdentidad INT(25) NOT NULL UNIQUE,
  usuaClave VARCHAR(25) NOT NULL,
  usuaNombres VARCHAR(35) NOT NULL,
  usuaApellido1 VARCHAR(15) NOT NULL,
  usuaApellido2 VARCHAR(15) NOT NULL,
  usuaTelefono INT(15) NOT NULL,
  FOREIGN KEY (casaId) REFERENCES CASAS(casaId) ON DELETE CASCADE
);
CREATE TABLE CONTADORES (
  contId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  casaId INT(5) NOT NULL,
  contNumero INT(15) NOT NULL,
  FOREIGN KEY (casaId) REFERENCES CASAS(casaId) ON DELETE CASCADE
);
CREATE TABLE HISTORIAL_CONTADORES (
  histIdC INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  contId  INT(5) NOT NULL,
  histRegistroC DECIMAL(4,2) NOT NULL,
  histFechaC DATE,
  FOREIGN KEY (contId) REFERENCES CONTADORES(contId) ON DELETE CASCADE
);
CREATE TABLE LOCACIONES (
  locaId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  locaNombre VARCHAR(25) NOT NULL
);
CREATE TABLE SENSORES (
  sensId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  locaId INT(5) NOT NULL,
  contId INT(5) NOT NULL,
  sensNumero INT(15) NOT NULL,
  FOREIGN KEY (locaId) REFERENCES LOCACIONES(locaId) ON DELETE CASCADE,
  FOREIGN KEY (contId) REFERENCES CONTADORES(contId) ON DELETE CASCADE
);
CREATE TABLE ACTIVIDADES (
  actiId INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  actiNombre VARCHAR(35) NOT NULL
);
CREATE TABLE DETALLE_ACTIVIDADES (
  actiIdD INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  usuaId  INT(5) NOT NULL,
  actiId  INT(5) NOT NULL,
  sensId  INT(5) NOT NULL,
  detaLimiteA DECIMAL(4,2) NOT NULL,
  UNIQUE (usuaId, actiId, sensId),
  FOREIGN KEY (usuaId) REFERENCES USUARIOS(usuaId) ON DELETE CASCADE,
  FOREIGN KEY (actiId) REFERENCES ACTIVIDADES(actiId) ON DELETE CASCADE,
  FOREIGN KEY (sensId) REFERENCES SENSORES(sensId) ON DELETE CASCADE
);
